import {
  MPinkJersey,
  MBlackJersey,
  MRedJersey,
  MYellowJersey,
  MultiTrackJacket,
  BlackTrackJacket,
  BlackTrackPant,
  RedTrackPant,
  FUBULogoBelt,
  Classic90sDenim,
  FubuCarpenterDenim,
  ClassicFubuDenim,
  FubuJeans,
  WomensWakandaForeverJoggers,
  WomensBlackPantherJogger,
  WomensBlackPantherLongSleeveTee,
  WomensBlackPantherTieDyeCrewneck,
} from "../assets";

export const PRODUCTS = [
  {
    id: 1,
    productName: "FUBU",
    productDescription: "OMBRE ICONIC LOGO TRACK JACKET",
    productPrice: 135,
    productImage: MultiTrackJacket,
    productCategory: "tops",
  },
  {
    id: 2,
    productName: "FUBU",
    productDescription: "BLACK ICONIC LOGO TRACK JACKET",
    productPrice: 135,
    productImage: BlackTrackJacket,
    productCategory: "tops",
  },
  {
    id: 3,
    productName: "FUBU",
    productDescription: "SHOCKING PINK 05 ICONIC JERSEY",
    productPrice: 100,
    productImage: MPinkJersey,
    productCategory: "tops",
  },

  {
    id: 4,
    productName: "FUBU",
    productDescription: "BLACK 05 ICONIC JERSEY",
    productPrice: 100,
    productImage: MBlackJersey,
    productCategory: "tops",
  },
  {
    id: 5,
    productName: "FUBU",
    productDescription: "RED 05 ICONIC JERSEY",
    productPrice: 100,
    productImage: MRedJersey,
    productCategory: "tops",
  },

  {
    id: 6,
    productName: "FUBU",
    productDescription: "CITRINE 05 ICONIC JERSEY",
    productPrice: 100,
    productImage: MYellowJersey,
    productCategory: "tops",
  },
  {
    id: 7,
    productName: "FUBU",
    productDescription: "ANTIQUE ARCHIVE LOGO CRYSTAL SWEATPANT",
    productPrice: 85,
    productImage: BlackTrackPant,
    productCategory: "bottoms",
  },

  {
    id: 8,
    productName: "FUBU",
    productDescription: "RED ARCHIVE LOGO CRYSTAL SWEATPANT",
    productPrice: 85,
    productImage: RedTrackPant,
    productCategory: "bottoms",
  },
  {
    id: 9,
    productName: "FUBU",
    productDescription: "ICONIC LOGO BELT",
    productPrice: 125,
    productImage: FUBULogoBelt,
    productCategory: "accessories",
  },
  {
    id: 10,
    productName: "Classic 90s Denim",
    productPrice: 50,
    productImage: Classic90sDenim,
    productCategory: "men",
  },
  {
    id: 11,
    productName: "Fubu Carpenter Denim",
    productPrice: 50,
    productImage: FubuCarpenterDenim,
    productCategory: "men",
  },
  {
    id: 12,
    productName: "Classic Fubu Denim",
    productPrice: 50,
    productImage: ClassicFubuDenim,
    productCategory: "men",
  },
  {
    id: 13,
    productName: "Fubu Jeans",
    productPrice: 50,
    productImage: FubuJeans,
    productCategory: "men",
  },
  {
    id: 14,
    productName: "Women's Wakanda Forever Joggers",
    productPrice: 50,
    productImage: WomensWakandaForeverJoggers,
    productCategory: "women",
  },
  {
    id: 15,
    productName: "Women's Black Panther Forever Joggers",
    productPrice: 50,
    productImage: WomensBlackPantherJogger,
    productCategory: "women",
  },
  {
    id: 16,
    productName: "Women's Black Panther Long Sleeve Tee",
    productPrice: 50,
    productImage: WomensBlackPantherLongSleeveTee,
    productCategory: "women",
  },
  {
    id: 17,
    productName: "Women's Black Panther Tie Dye Crewneck",
    productPrice: 50,
    productImage: WomensBlackPantherTieDyeCrewneck,
    productCategory: "women",
  },
];
